### ISSUE TITLE
It needs development else

### ISSUE THREAD

**Issue by ivose** [solutionforest/filament-translate-field#3]
public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Translate::make([])
                    ->columnSpanFull()
                    ->locales(['et', 'en', 'lv', 'ru'])
                    ->suffixLocaleLabel()
                    ->actions([
                        Action::make('fillDumpTitle')
                    ])
                    //->preformLocaleLabelUsing(fn(string $locale, string $label) => "[{$label}]")
                    ->schema([
					//why only such list works?????
                        TextInput::make('name')
                            ->label('Name')
                            ->required()
                            ->maxLength(128),
                        Textarea::make('description')
                            ->label('Description')
                            ->maxLength(65535), // or use any appropriate length
                        TextInput::make('link_rewrite')
                            ->label('Link Rewrite')
                            ->required()
                            ->maxLength(128),
                        TextInput::make('meta_title')
                            ->label('Meta Title')
                            ->maxLength(128),
                        TextInput::make('meta_keywords')
                            ->label('Meta Keywords')
                            ->maxLength(255),
                        Textarea::make('meta_description')
                            ->label('Meta Description')
                            ->maxLength(512),
						/**
						Here if i put the fields inside grids or section
						Section::make('Üldandmed')
                    ->description('Seada tootegrupp kategooria ja protsent')
                    ->columns(12)
                    ->schema([
					TextInput::make('name')
                            ->label('Name')... etc
							It displays only errors and 
							in function EditCategory->mound 
							parent::mount($record); simply doesn't work: 
					])
						*/
                    ])
            ]);
    }

**Comment by mstfkhazaal** [comment]
I don't understand the problem
i try this and it work

```
  public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Translate::make([
                    TextInput::make('name')
                        ->label('Name')
                        ->required()
                        ->maxLength(128),
                    Textarea::make('description')
                        ->label('Description')
                        ->maxLength(65535),
                    TextInput::make('link_rewrite')
                        ->label('Link Rewrite')
                        ->required()
                        ->maxLength(128),
                    TextInput::make('meta_title')
                        ->label('Meta Title')
                        ->maxLength(128),
                    TextInput::make('meta_keywords')
                        ->label('Meta Keywords')
                        ->maxLength(255),
                    Textarea::make('meta_description')
                        ->label('Meta Description')
                        ->maxLength(512),

                ])
                    ->columnSpanFull()
                    ->locales(['et', 'en', 'lv', 'ru'])
                    ->suffixLocaleLabel()
                    ->actions([
                        Action::make('fillDumpTitle')
                    ])
                    ->preformLocaleLabelUsing(fn(string $locale, string $label) => "[{$label}]")

            ]);
    }
```
