### ISSUE TITLE
Default locales not set

### ISSUE THREAD

**Issue by dmitrijsmihailovs** [solutionforest/filament-translate-field#6]
When locales are set in panel provider using defaultLocales method, they are not used in Translate field
```
FilamentTranslateFieldPlugin::make()
    ->defaultLocales(['en', 'es'])
```

```
Translate::make()
->schema(fn(string $locale) => [
    TextInput::make('name')
    ->required(),

    TextInput::make('slug')
     ->required(),
])->columnSpanFull(),
```

This example does not show any fields in form.
![image](https://github.com/solutionforest/filament-translate-field/assets/6555569/ae1b441a-6520-4e19-b657-e07d3c98533d)

**Comment by cklei-carly** [comment]
@dmitrijsmihailovs Which version of `solution-forest/filament-translate-field` you are using?

**Comment by dmitrijsmihailovs** [comment]
With the latest changes and moving to service provider, now it works.
